<?php
require '../_guard.php';
$eventId = (int) ($_GET['id'] ?? 0); $statement = db()->prepare('SELECT * FROM events WHERE id = ?'); $statement->execute([$eventId]); $event = $statement->fetch();
if (!$event) adminRedirect('events', 'message=' . urlencode('Event not found.'));
$errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') { $image = trim($_POST['image'] ?? ''); $title = trim($_POST['title'] ?? ''); $description = trim($_POST['description'] ?? ''); $eventDate = trim($_POST['event_date'] ?? ''); $eventTime = trim($_POST['event_time'] ?? ''); $location = trim($_POST['location'] ?? ''); $category = trim($_POST['category'] ?? ''); $status = ($_POST['status'] ?? '') === 'Inactive' ? 'Inactive' : 'Active'; foreach (['image' => $image, 'title' => $title, 'description' => $description, 'event date' => $eventDate, 'event time' => $eventTime, 'location' => $location, 'category' => $category] as $field => $value) if ($value === '') $errors[] = ucfirst($field) . ' is required.'; if (!$errors) { $update = db()->prepare('UPDATE events SET event_date = ?, event_time = ?, category = ?, title = ?, description = ?, image = ?, location = ?, status = ?, active = ? WHERE id = ?'); $update->execute([$eventDate, $eventTime, $category, $title, $description, $image, $location, $status, $status === 'Active' ? 1 : 0, $eventId]); adminRedirect('events', 'message=' . urlencode('Event updated successfully.')); } $event = array_merge($event, ['image' => $image, 'title' => $title, 'description' => $description, 'event_date' => $eventDate, 'event_time' => $eventTime, 'location' => $location, 'category' => $category, 'status' => $status]); }
$pageTitle = 'Edit event | LFT Admin';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($pageTitle) ?></title><link rel="stylesheet" href="../../assets/css/style.css"></head><body><main class="admin-app"><?php require '../sidebar.php'; ?><div class="admin-main"><header class="admin-topbar"><div><p class="section-label">EVENT CALENDAR</p><h1>Edit event</h1><p>Update <?= e($event['title']) ?>.</p></div><a class="text-link" href="index.php">Back to events</a><?php require "../profile.php"; ?></header><section class="admin-widget booking-detail"><?php foreach ($errors as $error): ?><div class="form-error"><?= e($error) ?></div><?php endforeach; ?><form class="admin-editor" method="post"><label>Event image<input name="image" value="<?= e($event['image']) ?>" required></label><label>Event title<input name="title" value="<?= e($event['title']) ?>" required></label><label>Description<textarea name="description" rows="4" required><?= e($event['description']) ?></textarea></label><label>Date<input name="event_date" type="date" value="<?= e($event['event_date']) ?>" required></label><label>Time<input name="event_time" type="time" value="<?= e($event['event_time']) ?>" required></label><label>Location<input name="location" value="<?= e($event['location']) ?>" required></label><label>Category<input name="category" value="<?= e($event['category']) ?>" required></label><label>Status<select name="status"><option <?= $event['status'] === 'Active' ? 'selected' : '' ?>>Active</option><option <?= $event['status'] === 'Inactive' ? 'selected' : '' ?>>Inactive</option></select></label><button class="btn btn-green" type="submit">SAVE CHANGES</button></form></section></div></main></body></html>
<?php
require '../_guard.php';
adminRedirect('events', 'edit_event=' . urlencode($_GET['id'] ?? ''));
