<?php
require '../_guard.php';
 $connection = db(); $search = trim($_GET['q'] ?? ''); $statusFilter = $_GET['status'] ?? ''; $message = $_GET['message'] ?? '';
 $allowedStatuses = ['Active', 'Inactive']; if (!in_array($statusFilter, $allowedStatuses, true)) $statusFilter = '';
 $conditions = []; $parameters = [];
 if ($search !== '') { $conditions[] = '(title LIKE ? OR description LIKE ? OR location LIKE ?)'; $term = '%' . $search . '%'; $parameters = [$term, $term, $term]; }
 if ($statusFilter !== '') { $conditions[] = 'status = ?'; $parameters[] = $statusFilter; }
 $statement = $connection->prepare('SELECT * FROM events ' . ($conditions ? 'WHERE ' . implode(' AND ', $conditions) . ' ' : '') . "ORDER BY event_date, event_time"); $statement->execute($parameters); $events = $statement->fetchAll();
 $pageTitle = 'Events | LFT Admin';
 ?>
 <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($pageTitle) ?></title><link rel="stylesheet" href="../../assets/css/style.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"></head><body><main class="admin-app"><?php require '../sidebar.php'; ?><div class="admin-main"><header class="admin-topbar"><div><p class="section-label">LFT DUMAGUETE</p><h1>Events</h1><p>Manage event images, details, schedules, locations, and status.</p></div><?php require '../profile.php'; ?></header><?php if ($message): ?><div class="success-message"><?= e($message) ?></div><?php endif; ?><section class="admin-widget booking-panel"><div class="widget-heading"><div><h2>Event calendar</h2><p><?= count($events) ?> <?= count($events) === 1 ? 'event' : 'events' ?></p></div><a class="btn btn-green" href="add.php">ADD EVENT</a></div><form class="booking-filters" method="get"><label for="event-search">Search</label><input id="event-search" name="q" value="<?= e($search) ?>" placeholder="Title, description, or location"><label for="event-status">Filter status</label><select id="event-status" name="status"><option value="">All statuses</option><?php foreach ($allowedStatuses as $status): ?><option value="<?= e($status) ?>" <?= $statusFilter === $status ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select><button class="btn btn-green" type="submit">FILTER</button><?php if ($search !== '' || $statusFilter !== ''): ?><a class="text-link" href="index.php">Clear</a><?php endif; ?></form><div class="booking-table"><div class="event-table-head"><span>Event</span><span>Date / time</span><span>Location</span><span>Status</span><span>Actions</span></div><?php if (!$events): ?><div class="empty-state">No events found.</div><?php else: foreach ($events as $event): ?><div class="event-table-row"><div><strong><?= e($event['title']) ?></strong><small><?= e($event['category']) ?> · <?= e($event['image']) ?></small></div><span><?= e(date('M j, Y', strtotime($event['event_date']))) ?><small><?= e(date('g:i A', strtotime($event['event_time']))) ?></small></span><span><?= e($event['location']) ?><small><?= e($event['description']) ?></small></span><span class="table-status <?= $event['status'] === 'Active' ? '' : 'status-cancelled' ?>"><?= e($event['status']) ?></span><div class="row-actions"><a class="text-link" href="edit.php?id=<?= (int) $event['id'] ?>">Edit</a><form method="post" action="delete.php" onsubmit="return confirm('Delete this event?');"><input type="hidden" name="id" value="<?= (int) $event['id'] ?>"><button class="danger-link" type="submit">Delete</button></form></div></div><?php endforeach; endif; ?></div></section></div></main></body></html>
