<?php
require '../_guard.php';
$connection = db(); $search = trim($_GET['q'] ?? ''); $status = $_GET['status'] ?? ''; $message = $_GET['message'] ?? '';
$statuses = ['Unread', 'Read']; if (!in_array($status, $statuses, true)) $status = '';
$conditions = []; $parameters = [];
if ($search !== '') { $conditions[] = '(sender LIKE ? OR email LIKE ? OR subject LIKE ?)'; $term = '%' . $search . '%'; $parameters = [$term, $term, $term]; }
if ($status !== '') { $conditions[] = 'status = ?'; $parameters[] = $status; }
$statement = $connection->prepare('SELECT * FROM messages ' . ($conditions ? 'WHERE ' . implode(' AND ', $conditions) . ' ' : '') . 'ORDER BY created_at DESC'); $statement->execute($parameters); $messages = $statement->fetchAll();
$pageTitle = 'Messages | LFT Admin';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($pageTitle) ?></title><link rel="stylesheet" href="../../assets/css/style.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"></head><body><main class="admin-app"><?php require '../sidebar.php'; ?><div class="admin-main"><header class="admin-topbar"><div><p class="section-label">LFT DUMAGUETE</p><h1>Messages</h1><p>Review contact messages from your visitors.</p></div><?php require '../profile.php'; ?></header><?php if ($message): ?><div class="success-message"><?= e($message) ?></div><?php endif; ?><section class="admin-widget booking-panel"><div class="widget-heading"><div><h2>Contact inbox</h2><p><?= count($messages) ?> <?= count($messages) === 1 ? 'message' : 'messages' ?></p></div></div><form class="booking-filters" method="get"><label for="message-search">Search</label><input id="message-search" name="q" value="<?= e($search) ?>" placeholder="Sender, email, or subject"><label for="message-status">Filter status</label><select id="message-status" name="status"><option value="">All statuses</option><?php foreach ($statuses as $item): ?><option <?= $status === $item ? 'selected' : '' ?>><?= e($item) ?></option><?php endforeach; ?></select><button class="btn btn-green" type="submit">FILTER</button></form><div class="booking-table"><div class="message-table-head"><span>Sender</span><span>Email</span><span>Subject</span><span>Date</span><span>Status</span><span>Action</span></div><?php if (!$messages): ?><div class="empty-state">No contact messages found.</div><?php else: foreach ($messages as $item): ?><div class="message-table-row"><strong><?= e($item['sender']) ?></strong><span><?= e($item['email']) ?></span><span><?= e($item['subject']) ?></span><span><?= e(date('M j, Y g:i A', strtotime($item['created_at']))) ?></span><span class="table-status <?= $item['status'] === 'Read' ? '' : 'status-pending' ?>"><?= e($item['status']) ?></span><div class="row-actions"><a class="text-link" href="view.php?id=<?= (int) $item['id'] ?>">View</a><form method="post" action="delete.php" onsubmit="return confirm('Delete this message?');"><input type="hidden" name="id" value="<?= (int) $item['id'] ?>"><button class="danger-link" type="submit">Delete</button></form></div></div><?php endforeach; endif; ?></div></section></div></main></body></html>
