<?php
require '../_guard.php';
$amenityId = (int) ($_GET['id'] ?? 0); $statement = db()->prepare('SELECT * FROM amenities WHERE id = ?'); $statement->execute([$amenityId]); $amenity = $statement->fetch();
if (!$amenity) adminRedirect('amenities', 'message=' . urlencode('Amenity not found.'));
$errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') { $icon = trim($_POST['icon'] ?? ''); $name = trim($_POST['name'] ?? ''); $description = trim($_POST['description'] ?? ''); $active = isset($_POST['active']) ? 1 : 0; foreach (['icon' => $icon, 'name' => $name, 'description' => $description] as $field => $value) if ($value === '') $errors[] = ucfirst($field) . ' is required.'; if (!$errors) { $update = db()->prepare('UPDATE amenities SET icon = ?, name = ?, description = ?, active = ? WHERE id = ?'); $update->execute([$icon, $name, $description, $active, $amenityId]); adminRedirect('amenities', 'message=' . urlencode('Amenity updated successfully.')); } $amenity = array_merge($amenity, compact('icon', 'name', 'description', 'active')); }
$pageTitle = 'Edit amenity | LFT Admin';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($pageTitle) ?></title><link rel="stylesheet" href="../../assets/css/style.css"></head><body><main class="admin-app"><?php require "../sidebar.php"; ?><div class="admin-main"><header class="admin-topbar"><div><p class="section-label">AMENITY CATALOG</p><h1>Edit an amenity</h1><p>Update <?= e($amenity['name']) ?>.</p></div><a class="text-link" href="index.php">Back to amenities</a><?php require "../profile.php"; ?></header><section class="admin-widget booking-detail"><?php foreach ($errors as $error): ?><div class="form-error"><?= e($error) ?></div><?php endforeach; ?><form class="admin-editor" method="post"><label>Icon class<input name="icon" value="<?= e($amenity['icon']) ?>" required></label><label>Name<input name="name" value="<?= e($amenity['name']) ?>" required></label><label>Description<textarea name="description" rows="4" required><?= e($amenity['description']) ?></textarea></label><label class="admin-checkbox"><input type="checkbox" name="active" <?= (int) $amenity['active'] === 1 ? 'checked' : '' ?>> Publish this amenity</label><button class="btn btn-green" type="submit">SAVE CHANGES</button></form></section></div></main></body></html>
