<?php
require '../../Includes/db.php';
$user = requireRole(['admin']);
$connection = db(); $notice = ''; $errors = [];
$settings = $connection->query('SELECT * FROM site_settings WHERE id = 1')->fetch();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
	$action = $_POST['action'] ?? '';
	if ($action === 'profile') { $name = trim($_POST['name'] ?? ''); $email = strtolower(trim($_POST['email'] ?? '')); if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) $errors[] = 'Enter a valid name and email.'; else { $update = $connection->prepare('UPDATE users SET name = ?, email = ? WHERE id = ?'); try { $update->execute([$name, $email, $user['id']]); $notice = 'Admin profile updated.'; $user['name'] = $name; $user['email'] = $email; } catch (PDOException $exception) { $errors[] = 'That email address is already in use.'; } } }
	if ($action === 'website') { $fields = ['website_name', 'email', 'phone', 'address', 'facebook', 'instagram']; $values = []; foreach ($fields as $field) $values[$field] = trim($_POST[$field] ?? ''); if (in_array('', array_slice($values, 0, 4), true)) $errors[] = 'Website name, email, phone, and address are required.'; else { $update = $connection->prepare('UPDATE site_settings SET website_name = ?, email = ?, phone = ?, address = ?, facebook = ?, instagram = ?, updated_at = CURRENT_TIMESTAMP WHERE id = 1'); $update->execute(array_values($values)); $settings = array_merge($settings, $values); $notice = 'Website information updated.'; } }
	if ($action === 'password') { $current = $_POST['current_password'] ?? ''; $new = $_POST['new_password'] ?? ''; $confirm = $_POST['confirm_password'] ?? ''; $account = $connection->prepare('SELECT password_hash FROM users WHERE id = ?'); $account->execute([$user['id']]); $hash = $account->fetchColumn(); if (!password_verify($current, $hash)) $errors[] = 'Current password is incorrect.'; elseif (strlen($new) < 8 || $new !== $confirm) $errors[] = 'New passwords must match and be at least 8 characters.'; else { $update = $connection->prepare('UPDATE users SET password_hash = ? WHERE id = ?'); $update->execute([password_hash($new, PASSWORD_DEFAULT), $user['id']]); $notice = 'Password changed successfully.'; } }
}
$pageTitle = 'Settings | LFT Admin';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($pageTitle) ?></title><link rel="stylesheet" href="../../assets/css/style.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"></head><body><main class="admin-app"><?php require '../sidebar.php'; ?><div class="admin-main"><header class="admin-topbar"><div><p class="section-label">LFT DUMAGUETE</p><h1>Settings</h1><p>Manage your profile and website information.</p></div><?php require '../profile.php'; ?></header><?php foreach ($errors as $error): ?><div class="form-error"><?= e($error) ?></div><?php endforeach; ?><?php if ($notice): ?><div class="success-message"><?= e($notice) ?></div><?php endif; ?><section class="settings-grid"><article class="admin-widget settings-card"><h2>Admin profile</h2><form class="admin-editor" method="post"><input type="hidden" name="action" value="profile"><label>Name<input name="name" value="<?= e($user['name']) ?>" required></label><label>Email<input name="email" type="email" value="<?= e($user['email']) ?>" required></label><button class="btn btn-green" type="submit">SAVE PROFILE</button></form></article><article class="admin-widget settings-card"><h2>Website information</h2><form class="admin-editor" method="post"><input type="hidden" name="action" value="website"><label>Website name<input name="website_name" value="<?= e($settings['website_name']) ?>" required></label><label>Email<input name="email" type="email" value="<?= e($settings['email']) ?>" required></label><label>Phone<input name="phone" value="<?= e($settings['phone']) ?>" required></label><label>Address<textarea name="address" rows="3" required><?= e($settings['address']) ?></textarea></label><label>Facebook link<input name="facebook" type="url" value="<?= e($settings['facebook']) ?>"></label><label>Instagram link<input name="instagram" type="url" value="<?= e($settings['instagram']) ?>"></label><button class="btn btn-green" type="submit">SAVE WEBSITE INFO</button></form></article><article class="admin-widget settings-card"><h2>Change password</h2><form class="admin-editor" method="post"><input type="hidden" name="action" value="password"><label>Current password<input name="current_password" type="password" required></label><label>New password<input name="new_password" type="password" minlength="8" required></label><label>Confirm new password<input name="confirm_password" type="password" minlength="8" required></label><button class="btn btn-green" type="submit">CHANGE PASSWORD</button></form></article></section></div></main></body></html>
